import { globalBuddhistLocale } from "@/configs/locale";
import { themeConfig } from "@/configs/theme";
import { toastOptions } from "@/configs/toast";
import "@/styles/globals.css";
import { ConfigProvider } from "antd";
import dayjs from "dayjs";
import "dayjs/locale/th";
import buddhistEra from "dayjs/plugin/buddhistEra";
import type { Metadata } from "next";
import { Prompt } from "next/font/google";
import { Suspense } from "react";
import { ToastContainer } from "react-toastify";

dayjs.extend(buddhistEra);
dayjs.locale("th");

const prompt = Prompt({
  weight: ["300", "400", "500", "600", "700", "800", "900"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-prompt",
});

export const metadata: Metadata = {
  title: "Next15",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${prompt.className} antialiased`}>
      <body>
        <Suspense>
          <ConfigProvider theme={themeConfig} locale={globalBuddhistLocale}>
            {children}
          </ConfigProvider>
        </Suspense>
        <ToastContainer {...toastOptions} />
      </body>
    </html>
  );
}
